# -*- coding: utf-8 -*-
"""Assignment1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CYBqJN3UPVJOXlZY1LBxN-QHHVTcrvyi
"""

import random
n = 100000    #Number of times the experiment is done.
Xctr = [0,0,0,0]                                     #Counter Variable that counts the number of times X attains each value from the set {0,1,2,3}
for j in range(n):                                   #j counts how many times the experiment is obtained, also, experiment number. 
  r = 0
  for i in range(3):                                 #Throw number in that experiment
    D1 = random.randint(1,6)                         #Number on dice 1
    D2 = random.randint(1,6)                         #Number on dice 2
    if D1== D2:
      r+= 1
  Xctr[r] += 1
print("SIMULATION\n")
for i in range(4):
  print(f"\n\t\tPr(X={i}) = {Xctr[i]/n} ")
print("\nTHEORY\n")
print(f"\n\t\tPr(X=0) = 0.5787")
print(f"\n\t\tPr(X=1) = 0.3469")
print(f"\n\t\tPr(X=2) = 0.0694")
print(f"\n\t\tPr(X=3) = 0.0046")